/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Registro;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

import javax.swing.JOptionPane;
import modelo.Jugador;
import modelo.Equipo;

/**
 *
 * @author TonyMontanaPC
 */
public class InscribirJugador extends javax.swing.JFrame {
    ArrayList array = new ArrayList<>();
    DefaultListModel modelo = new DefaultListModel();       
    /**
     * Creates new form InscribirJugador
     */
    public InscribirJugador() {
        initComponents();
        
        modelo = new DefaultListModel();
        jlist_equipos.setModel(modelo);
        
        rbtn_group.add(rbtn_1);
        rbtn_group.add(rbtn_2);
        rbtn_group.add(rbtn_3);
        rbtn_group.add(rbtn_4);
        rbtn_group.add(rbtn_5);
        rbtn_group.add(rbtn_6);
        rbtn_group.add(rbtn_7);
        rbtn_group.add(rbtn_8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtn_group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlist_equipos = new javax.swing.JList<>();
        rbtn_1 = new javax.swing.JRadioButton();
        rbtn_2 = new javax.swing.JRadioButton();
        rbtn_4 = new javax.swing.JRadioButton();
        rbtn_5 = new javax.swing.JRadioButton();
        rbtn_3 = new javax.swing.JRadioButton();
        rbtn_6 = new javax.swing.JRadioButton();
        rbtn_7 = new javax.swing.JRadioButton();
        rbtn_8 = new javax.swing.JRadioButton();
        btn_inscribir = new javax.swing.JButton();
        btn_mostrar_equipos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Inscribir jugador:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Posicion:");

        jScrollPane1.setViewportView(jlist_equipos);

        rbtn_1.setText("Lateral");

        rbtn_2.setText("Central");

        rbtn_4.setText("Volante");

        rbtn_5.setText("Medio centro");

        rbtn_3.setText("Contención");

        rbtn_6.setText("Extremo");

        rbtn_7.setText("9 de area");

        rbtn_8.setText("Portero");

        btn_inscribir.setText("Inscribir");
        btn_inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inscribirActionPerformed(evt);
            }
        });

        btn_mostrar_equipos.setText("Mostrar equipos");
        btn_mostrar_equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrar_equiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_inscribir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txt_apellido))
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn_2)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn_5)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn_8))))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mostrar_equipos))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_2)
                            .addComponent(rbtn_3)
                            .addComponent(rbtn_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_4)
                            .addComponent(rbtn_5)
                            .addComponent(rbtn_6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_7)
                            .addComponent(rbtn_8))
                        .addGap(18, 18, 18)
                        .addComponent(btn_inscribir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_mostrar_equipos)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inscribirActionPerformed
        Registro reg = new Registro();
        String pnombre, apaterno, posicion;
        pnombre = this.txt_nombre.getText();
        apaterno = this.txt_apellido.getText();
        posicion = "";
        boolean flag = false;
        if (rbtn_1.isSelected()) {
            posicion = rbtn_1.getText();
        }
        if (rbtn_2.isSelected()) {
            posicion = rbtn_2.getText();
        }
        if (rbtn_3.isSelected()) {
            posicion = rbtn_3.getText();
        }
        if (rbtn_4.isSelected()) {
            posicion = rbtn_4.getText();
        }
        if (rbtn_5.isSelected()) {
            posicion = rbtn_5.getText();
        }
        if (rbtn_6.isSelected()) {
            posicion = rbtn_6.getText();
        }
        if (rbtn_7.isSelected()) {
            posicion = rbtn_7.getText();
        }
        if (rbtn_8.isSelected()) {
            posicion = rbtn_8.getText();
        }
        if (posicion.isEmpty()) {
            flag = true;
        }
        Jugador jugador = new Jugador(0, pnombre, apaterno, posicion, 0);
        if (flag == true) {
            JOptionPane.showMessageDialog(this, "Seleccione una posicion", "Aviso", 1);
        }
        if (flag == false) {
            try {
                reg.agregarJugador(jugador);
                JOptionPane.showMessageDialog(this, "El jugador se agrego correctamente", "Aviso", 1);
            } catch (HeadlessException e) {
                System.out.println("Error al agregar jugador" + e.getMessage());
            }
        }

    }//GEN-LAST:event_btn_inscribirActionPerformed

    private void btn_mostrar_equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrar_equiposActionPerformed
        modelo.removeAllElements();
        Registro reg = new Registro();
        String nombre_equipo = "";
        List<Equipo> lista1 = reg.listarEquipos();
        
        for (Equipo equipo : lista1) {
            nombre_equipo = equipo.getNombre();
            array.add(nombre_equipo);
        }
        
        for (int i = 0; i < 10; i++) {
            modelo.addElement();
        }
        
        
    }//GEN-LAST:event_btn_mostrar_equiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscribirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscribirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscribirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscribirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscribirJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inscribir;
    private javax.swing.JButton btn_mostrar_equipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlist_equipos;
    private javax.swing.JRadioButton rbtn_1;
    private javax.swing.JRadioButton rbtn_2;
    private javax.swing.JRadioButton rbtn_3;
    private javax.swing.JRadioButton rbtn_4;
    private javax.swing.JRadioButton rbtn_5;
    private javax.swing.JRadioButton rbtn_6;
    private javax.swing.JRadioButton rbtn_7;
    private javax.swing.JRadioButton rbtn_8;
    private javax.swing.ButtonGroup rbtn_group;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
