/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import controlador.Registro;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Equipo;

/**
 *
 * @author TonyMontanaPC
 */
public class InscribirEquipo extends javax.swing.JFrame {

    /**
     * Creates new form InscribirEquipo
     */
    public InscribirEquipo() {
        initComponents();

        rbtngroup_1.add(rbtn_estadio1);
        rbtngroup_1.add(rbtn_estadio2);
        rbtngroup_1.add(rbtn_estadio3);
        rbtngroup_1.add(rbtn_estadio4);
        rbtngroup_1.add(rbtn_estadio5);
        rbtngroup_1.add(rbtn_estadio6);
        rbtngroup_1.add(rbtn_estadio7);
        rbtngroup_1.add(rbtn_estadio8);
        rbtngroup_1.add(rbtn_estadio9);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngroup_1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        rbtn_estadio1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbtn_estadio2 = new javax.swing.JRadioButton();
        rbtn_estadio3 = new javax.swing.JRadioButton();
        rbtn_estadio4 = new javax.swing.JRadioButton();
        rbtn_estadio5 = new javax.swing.JRadioButton();
        rbtn_estadio6 = new javax.swing.JRadioButton();
        rbtn_estadio7 = new javax.swing.JRadioButton();
        rbtn_estadio8 = new javax.swing.JRadioButton();
        rbtn_estadio9 = new javax.swing.JRadioButton();
        btn_inscribir_partido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_mostrar_equipos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_id_equipo_eliminar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Inscribir equipo:");

        rbtn_estadio1.setText("Wembley");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Seleccione cancha local:");

        rbtn_estadio2.setText("Camp nou");

        rbtn_estadio3.setText("Santiago Bernabéu");

        rbtn_estadio4.setText("Estadio monumental");

        rbtn_estadio5.setText("Bombonera");

        rbtn_estadio6.setText("Maracanã");

        rbtn_estadio7.setText("Old trafford");

        rbtn_estadio8.setText("Sausalito");

        rbtn_estadio9.setText("Elías figueroa");

        btn_inscribir_partido.setText("Inscribir equipo");
        btn_inscribir_partido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inscribir_partidoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID equipo", "Nombre", "Cancha local"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_mostrar_equipos.setText("Mostrar equipos");
        btn_mostrar_equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrar_equiposActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Eliminar equipo:");

        jLabel5.setText("Ingrese id del equipo que desea eliminar:");

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_estadio1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtn_estadio2)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_estadio3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_estadio4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtn_estadio5)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_estadio6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_estadio7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtn_estadio8)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_estadio9))
                            .addComponent(btn_inscribir_partido)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_mostrar_equipos))
                        .addGap(166, 166, 166))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_id_equipo_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(173, 173, 173)
                        .addComponent(btn_volver)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_mostrar_equipos)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_estadio1)
                            .addComponent(rbtn_estadio2)
                            .addComponent(rbtn_estadio3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_estadio4)
                            .addComponent(rbtn_estadio5)
                            .addComponent(rbtn_estadio6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_estadio7)
                            .addComponent(rbtn_estadio8)
                            .addComponent(rbtn_estadio9))
                        .addGap(18, 18, 18)
                        .addComponent(btn_inscribir_partido))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_equipo_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_volver))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inscribir_partidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inscribir_partidoActionPerformed
        Registro reg = new Registro();
        int id_equipo;
        String nombre = this.txt_nombre.getText();
        String cancha_local = null;

        if (rbtn_estadio1.isSelected()) {
            cancha_local = rbtn_estadio1.getText();
        }
        if (rbtn_estadio2.isSelected()) {
            cancha_local = rbtn_estadio2.getText();
        }
        if (rbtn_estadio3.isSelected()) {
            cancha_local = rbtn_estadio3.getText();
        }
        if (rbtn_estadio4.isSelected()) {
            cancha_local = rbtn_estadio4.getText();
        }
        if (rbtn_estadio5.isSelected()) {
            cancha_local = rbtn_estadio5.getText();
        }
        if (rbtn_estadio6.isSelected()) {
            cancha_local = rbtn_estadio6.getText();
        }
        if (rbtn_estadio7.isSelected()) {
            cancha_local = rbtn_estadio7.getText();
        }
        if (rbtn_estadio8.isSelected()) {
            cancha_local = rbtn_estadio8.getText();
        }
        if (rbtn_estadio9.isSelected()) {
            cancha_local = rbtn_estadio9.getText();
        }
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre para el equipo", "Aviso", 1);
        }
        Equipo equipo = new Equipo(0, nombre, cancha_local);
        try {
        reg.agregarEquipo(equipo);
        JOptionPane.showMessageDialog(this, "El equipo fue ingresado correctamente", "Aviso", 1);
        } catch (Exception e) {
            System.out.println("No se pudo agregar equipo");
        }
        
    }//GEN-LAST:event_btn_inscribir_partidoActionPerformed

    private void btn_mostrar_equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrar_equiposActionPerformed
        int id_equipo;
        String nombre, cancha_local;
        Registro reg = new Registro();
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        modelo.setRowCount(0);
        List<Equipo> lista = reg.listarEquipos();
        for (Equipo equipo : lista) {
            id_equipo = equipo.getId_equipo();
            nombre = equipo.getNombre();
            cancha_local = equipo.getCancha_local();
            modelo.addRow(new Object[]{id_equipo, nombre, cancha_local});
        }

    }//GEN-LAST:event_btn_mostrar_equiposActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        boolean flag = false;
        Registro reg = new Registro();
        int id_equipo = Integer.parseInt(this.txt_id_equipo_eliminar.getText());
        List<Equipo> lista = reg.listarEquipos();
        for (Equipo equipo : lista) {            
            if (equipo.getId_equipo()==id_equipo) {                
                flag=true;
                break;
            }
        }
        if (flag==false) {
            JOptionPane.showMessageDialog(this, "El equipo ingresado no existe", "Avicci", 1);         
        }
        if (flag==true) {
            reg.eliminarEquipo(id_equipo);
            JOptionPane.showMessageDialog(this, "El equipo fue eliminado correctamente", "Aviso", 1);
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        dispose();
        new Menú().setVisible(true);
    }//GEN-LAST:event_btn_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscribirEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscribirEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscribirEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscribirEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscribirEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_inscribir_partido;
    private javax.swing.JButton btn_mostrar_equipos;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbtn_estadio1;
    private javax.swing.JRadioButton rbtn_estadio2;
    private javax.swing.JRadioButton rbtn_estadio3;
    private javax.swing.JRadioButton rbtn_estadio4;
    private javax.swing.JRadioButton rbtn_estadio5;
    private javax.swing.JRadioButton rbtn_estadio6;
    private javax.swing.JRadioButton rbtn_estadio7;
    private javax.swing.JRadioButton rbtn_estadio8;
    private javax.swing.JRadioButton rbtn_estadio9;
    private javax.swing.ButtonGroup rbtngroup_1;
    private javax.swing.JTextField txt_id_equipo_eliminar;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
